// ========================================
// Mardi Gras 2026 - Data
// ========================================
// This file contains all the parade and throws data.
// Edit this file to update your actual counts and weights.
// 
// DATA STRUCTURE:
// - Beads are now organized by: beads[color][parade][type]
//   where type is "medallion" or "regular"
// - Parades now include keyName field for consistent referencing
// - "unaffiliated" represents non-branded beads caught during parades

const mardiGrasData = {
    "parades": [
        {
            "name": "Krewe of Druids", 
            "shortName": "Druids",
            "keyName": "druids",
            "date": "Wed Feb 11 2026",
            "time": "6:15 PM",
            "logo": "logos/krewe-of-druids.png"
        },
        {
            "name": "Krewe of Alla", 
            "shortName": "Alla",
            "keyName": "alla",
            "date": "Wed Feb 11 2026",
            "time": "7:00 PM",
            "logo": "logos/krewe-of-alla.jpg"
        },
        {
            "name": "Knights of Chaos", 
            "shortName": "Chaos",
            "keyName": "chaos",
            "date": "Thu Feb 12 2026",
            "time": "4:30 PM",
            "logo": "logos/knights-of-choas.png"
        },
        {
            "name": "Knights of Babylon", 
            "shortName": "Babylon",
            "keyName": "babylon",
            "date": "Thu Feb 12 2026",
            "time": "5:30 PM",
            "logo": "logos/knights-of-babylon.png"
        },
        {
            "name": "Krewe of Muses", 
            "shortName": "Muses",
            "keyName": "muses",
            "date": "Thu Feb 12 2026",
            "time": "6:00 PM",
            "logo": "logos/krewe-of-muses.jpg"
        },
        {
            "name": "Krewe of Hermes", 
            "shortName": "Hermes",
            "keyName": "hermes",
            "date": "Fri Feb 13 2026",
            "time": "5:30 PM",
            "logo": "logos/krewe-of-hermes.jpg"
        },
        {
            "name": "Krewe d'Etat", 
            "shortName": "d'Etat",
            "keyName": "detat",
            "date": "Fri Feb 13 2026",
            "time": "6:30 PM",
            "logo": "logos/krewe-d-etat.png"
        },
        {
            "name": "Krewe of Morpheus", 
            "shortName": "Morpheus",
            "keyName": "morpheus",
            "date": "Fri Feb 13 2026",
            "time": "7:00 PM",
            "logo": "logos/krewe-of-morpheus.png"
        },
        {
            "name": "Krewe of Iris",
            "shortName": "Iris",
            "keyName": "iris", 
            "date": "Sat Feb 14 2026",
            "time": "11:00 AM",
            "logo": "logos/krewe-of-iris.jpg"
        },
        {
            "name": "Krewe of Tucks", 
            "shortName": "Tucks",
            "keyName": "tucks",
            "date": "Sat Feb 14 2026",
            "time": "12:30 PM",
            "logo": "logos/krewe-of-tucks.png"
        },
        {
            "name": "Krewe of Okeanos", 
            "shortName": "Okeanos",
            "keyName": "okeanos",
            "date": "Sun Feb 15 2026",
            "time": "11:00 AM",
            "logo": "logos/krewe-of-okeanos.png"
        },
        {
            "name": "Krewe of Mid-City", 
            "shortName": "Mid-City",
            "keyName": "midcity",
            "date": "Sun Feb 15 2026",
            "time": "11:45 AM",
            "logo": "logos/krewe-of-mid-city.jpg"
        },
        {
            "name": "Krewe of Thoth", 
            "shortName": "Thoth",
            "keyName": "thoth",
            "date": "Sun Feb 15 2026",
            "time": "12:00 PM",
            "logo": "logos/krewe-of-thoth.png"
        },
        {
            "name": "Krewe of Bacchus", 
            "shortName": "Bacchus",
            "keyName": "bacchus",
            "date": "Sun Feb 15 2026",
            "time": "5:10 PM",
            "logo": "logos/krewe-of-bacchus.png"
        },
        {
            "name": "Krewe of Proteus",
            "shortName": "Proteus", 
            "keyName": "proteus",
            "date": "Mon Feb 16 2026",
            "time": "5:15 PM",
            "logo": "logos/krewe-of-proteus.png"
        },
        {
            "name": "Krewe of Orpheus", 
            "shortName": "Orpheus",
            "keyName": "orpheus",
            "date": "Mon Feb 16 2026",
            "time": "6:00 PM",
            "logo": "logos/krewe-of-orpheus.png"
        }
    ],

    "beadTypes": ["black", "orange", "glass", "red", "white", "blue", "pink", "silver", "green", "purple", "gold", "lightup", "special", "huge"],
    
    "beads": {
        "purple": {
            "unaffiliated": {"medallion": {"weight": 18, "count": 1}, "regular": {"weight": 95, "count": 6}},
            "druids": {"medallion": {"weight": 52, "count": 2}, "regular": {"weight": 182, "count": 10}},
            "alla": {"medallion": {"weight": 62, "count": 2}, "regular": {"weight": 125, "count": 8}},
            "chaos": {"medallion": {"weight": 87, "count": 3}, "regular": {"weight": 211, "count": 12}},
            "babylon": {"medallion": {"weight": 94, "count": 3}, "regular": {"weight": 218, "count": 13}},
            "muses": {"medallion": {"weight": 125, "count": 4}, "regular": {"weight": 320, "count": 19}},
            "hermes": {"medallion": {"weight": 109, "count": 4}, "regular": {"weight": 280, "count": 16}},
            "detat": {"medallion": {"weight": 74, "count": 3}, "regular": {"weight": 193, "count": 11}},
            "morpheus": {"medallion": {"weight": 96, "count": 3}, "regular": {"weight": 238, "count": 14}},
            "iris": {"medallion": {"weight": 131, "count": 4}, "regular": {"weight": 325, "count": 20}},
            "tucks": {"medallion": {"weight": 118, "count": 4}, "regular": {"weight": 305, "count": 18}},
            "okeanos": {"medallion": {"weight": 105, "count": 4}, "regular": {"weight": 273, "count": 15}},
            "midcity": {"medallion": {"weight": 98, "count": 3}, "regular": {"weight": 247, "count": 15}},
            "thoth": {"medallion": {"weight": 143, "count": 5}, "regular": {"weight": 369, "count": 22}},
            "bacchus": {"medallion": {"weight": 187, "count": 6}, "regular": {"weight": 500, "count": 30}},
            "proteus": {"medallion": {"weight": 149, "count": 5}, "regular": {"weight": 385, "count": 23}},
            "orpheus": {"medallion": {"weight": 171, "count": 6}, "regular": {"weight": 452, "count": 27}}
        },
        "green": {
            "unaffiliated": {"medallion": {"weight": 15, "count": 1}, "regular": {"weight": 83, "count": 5}},
            "druids": {"medallion": {"weight": 48, "count": 2}, "regular": {"weight": 150, "count": 8}},
            "alla": {"medallion": {"weight": 55, "count": 2}, "regular": {"weight": 112, "count": 7}},
            "chaos": {"medallion": {"weight": 79, "count": 3}, "regular": {"weight": 197, "count": 11}},
            "babylon": {"medallion": {"weight": 86, "count": 3}, "regular": {"weight": 203, "count": 12}},
            "muses": {"medallion": {"weight": 118, "count": 4}, "regular": {"weight": 294, "count": 17}},
            "hermes": {"medallion": {"weight": 101, "count": 3}, "regular": {"weight": 255, "count": 15}},
            "detat": {"medallion": {"weight": 68, "count": 2}, "regular": {"weight": 177, "count": 11}},
            "morpheus": {"medallion": {"weight": 88, "count": 3}, "regular": {"weight": 224, "count": 13}},
            "iris": {"medallion": {"weight": 121, "count": 4}, "regular": {"weight": 302, "count": 18}},
            "tucks": {"medallion": {"weight": 109, "count": 4}, "regular": {"weight": 280, "count": 16}},
            "okeanos": {"medallion": {"weight": 98, "count": 3}, "regular": {"weight": 247, "count": 15}},
            "midcity": {"medallion": {"weight": 88, "count": 3}, "regular": {"weight": 224, "count": 13}},
            "thoth": {"medallion": {"weight": 133, "count": 5}, "regular": {"weight": 345, "count": 20}},
            "bacchus": {"medallion": {"weight": 176, "count": 6}, "regular": {"weight": 469, "count": 28}},
            "proteus": {"medallion": {"weight": 139, "count": 5}, "regular": {"weight": 359, "count": 21}},
            "orpheus": {"medallion": {"weight": 161, "count": 5}, "regular": {"weight": 428, "count": 26}}
        },
        "gold": {
            "unaffiliated": {"medallion": {"weight": 17, "count": 1}, "regular": {"weight": 95, "count": 6}},
            "druids": {"medallion": {"weight": 51, "count": 2}, "regular": {"weight": 161, "count": 9}},
            "alla": {"medallion": {"weight": 58, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "chaos": {"medallion": {"weight": 83, "count": 3}, "regular": {"weight": 204, "count": 12}},
            "babylon": {"medallion": {"weight": 89, "count": 3}, "regular": {"weight": 212, "count": 13}},
            "muses": {"medallion": {"weight": 122, "count": 4}, "regular": {"weight": 312, "count": 18}},
            "hermes": {"medallion": {"weight": 106, "count": 4}, "regular": {"weight": 272, "count": 15}},
            "detat": {"medallion": {"weight": 71, "count": 2}, "regular": {"weight": 185, "count": 11}},
            "morpheus": {"medallion": {"weight": 92, "count": 3}, "regular": {"weight": 231, "count": 14}},
            "iris": {"medallion": {"weight": 125, "count": 4}, "regular": {"weight": 320, "count": 19}},
            "tucks": {"medallion": {"weight": 113, "count": 4}, "regular": {"weight": 288, "count": 17}},
            "okeanos": {"medallion": {"weight": 102, "count": 4}, "regular": {"weight": 265, "count": 15}},
            "midcity": {"medallion": {"weight": 94, "count": 3}, "regular": {"weight": 240, "count": 14}},
            "thoth": {"medallion": {"weight": 138, "count": 5}, "regular": {"weight": 363, "count": 21}},
            "bacchus": {"medallion": {"weight": 182, "count": 6}, "regular": {"weight": 486, "count": 29}},
            "proteus": {"medallion": {"weight": 144, "count": 5}, "regular": {"weight": 379, "count": 22}},
            "orpheus": {"medallion": {"weight": 167, "count": 6}, "regular": {"weight": 445, "count": 26}}
        },
        "red": {
            "unaffiliated": {"medallion": {"weight": 12, "count": 1}, "regular": {"weight": 55, "count": 3}},
            "druids": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 102, "count": 6}},
            "alla": {"medallion": {"weight": 38, "count": 1}, "regular": {"weight": 74, "count": 5}},
            "chaos": {"medallion": {"weight": 54, "count": 2}, "regular": {"weight": 135, "count": 8}},
            "babylon": {"medallion": {"weight": 48, "count": 2}, "regular": {"weight": 119, "count": 7}},
            "muses": {"medallion": {"weight": 68, "count": 2}, "regular": {"weight": 177, "count": 11}},
            "hermes": {"medallion": {"weight": 62, "count": 2}, "regular": {"weight": 161, "count": 10}},
            "detat": {"medallion": {"weight": 44, "count": 1}, "regular": {"weight": 112, "count": 7}},
            "morpheus": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 142, "count": 8}},
            "iris": {"medallion": {"weight": 74, "count": 2}, "regular": {"weight": 193, "count": 12}},
            "tucks": {"medallion": {"weight": 66, "count": 2}, "regular": {"weight": 168, "count": 10}},
            "okeanos": {"medallion": {"weight": 59, "count": 2}, "regular": {"weight": 153, "count": 9}},
            "midcity": {"medallion": {"weight": 53, "count": 2}, "regular": {"weight": 136, "count": 8}},
            "thoth": {"medallion": {"weight": 81, "count": 3}, "regular": {"weight": 208, "count": 12}},
            "bacchus": {"medallion": {"weight": 108, "count": 4}, "regular": {"weight": 281, "count": 16}},
            "proteus": {"medallion": {"weight": 87, "count": 3}, "regular": {"weight": 225, "count": 13}},
            "orpheus": {"medallion": {"weight": 99, "count": 3}, "regular": {"weight": 257, "count": 15}}
        },
        "blue": {
            "unaffiliated": {"medallion": {"weight": 14, "count": 1}, "regular": {"weight": 75, "count": 4}},
            "druids": {"medallion": {"weight": 42, "count": 2}, "regular": {"weight": 125, "count": 7}},
            "alla": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 98, "count": 6}},
            "chaos": {"medallion": {"weight": 67, "count": 2}, "regular": {"weight": 167, "count": 10}},
            "babylon": {"medallion": {"weight": 61, "count": 2}, "regular": {"weight": 151, "count": 9}},
            "muses": {"medallion": {"weight": 88, "count": 3}, "regular": {"weight": 224, "count": 13}},
            "hermes": {"medallion": {"weight": 78, "count": 3}, "regular": {"weight": 200, "count": 11}},
            "detat": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 142, "count": 8}},
            "morpheus": {"medallion": {"weight": 69, "count": 2}, "regular": {"weight": 176, "count": 11}},
            "iris": {"medallion": {"weight": 93, "count": 3}, "regular": {"weight": 241, "count": 14}},
            "tucks": {"medallion": {"weight": 84, "count": 3}, "regular": {"weight": 214, "count": 12}},
            "okeanos": {"medallion": {"weight": 75, "count": 3}, "regular": {"weight": 192, "count": 11}},
            "midcity": {"medallion": {"weight": 66, "count": 2}, "regular": {"weight": 168, "count": 10}},
            "thoth": {"medallion": {"weight": 99, "count": 3}, "regular": {"weight": 257, "count": 15}},
            "bacchus": {"medallion": {"weight": 133, "count": 5}, "regular": {"weight": 345, "count": 20}},
            "proteus": {"medallion": {"weight": 108, "count": 4}, "regular": {"weight": 281, "count": 16}},
            "orpheus": {"medallion": {"weight": 124, "count": 4}, "regular": {"weight": 321, "count": 19}}
        },
        "pink": {
            "unaffiliated": {"medallion": {"weight": 10, "count": 1}, "regular": {"weight": 46, "count": 2}},
            "druids": {"medallion": {"weight": 28, "count": 1}, "regular": {"weight": 84, "count": 5}},
            "alla": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 66, "count": 4}},
            "chaos": {"medallion": {"weight": 46, "count": 2}, "regular": {"weight": 110, "count": 6}},
            "babylon": {"medallion": {"weight": 38, "count": 1}, "regular": {"weight": 96, "count": 6}},
            "muses": {"medallion": {"weight": 62, "count": 2}, "regular": {"weight": 161, "count": 10}},
            "hermes": {"medallion": {"weight": 53, "count": 2}, "regular": {"weight": 136, "count": 8}},
            "detat": {"medallion": {"weight": 38, "count": 1}, "regular": {"weight": 96, "count": 6}},
            "morpheus": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "iris": {"medallion": {"weight": 68, "count": 2}, "regular": {"weight": 177, "count": 11}},
            "tucks": {"medallion": {"weight": 59, "count": 2}, "regular": {"weight": 153, "count": 9}},
            "okeanos": {"medallion": {"weight": 53, "count": 2}, "regular": {"weight": 136, "count": 8}},
            "midcity": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "thoth": {"medallion": {"weight": 71, "count": 2}, "regular": {"weight": 185, "count": 11}},
            "bacchus": {"medallion": {"weight": 96, "count": 3}, "regular": {"weight": 249, "count": 15}},
            "proteus": {"medallion": {"weight": 77, "count": 3}, "regular": {"weight": 201, "count": 11}},
            "orpheus": {"medallion": {"weight": 87, "count": 3}, "regular": {"weight": 225, "count": 13}}
        },
        "white": {
            "unaffiliated": {"medallion": {"weight": 13, "count": 1}, "regular": {"weight": 65, "count": 3}},
            "druids": {"medallion": {"weight": 36, "count": 1}, "regular": {"weight": 109, "count": 7}},
            "alla": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 82, "count": 5}},
            "chaos": {"medallion": {"weight": 58, "count": 2}, "regular": {"weight": 140, "count": 8}},
            "babylon": {"medallion": {"weight": 52, "count": 2}, "regular": {"weight": 126, "count": 7}},
            "muses": {"medallion": {"weight": 74, "count": 2}, "regular": {"weight": 193, "count": 12}},
            "hermes": {"medallion": {"weight": 66, "count": 2}, "regular": {"weight": 168, "count": 10}},
            "detat": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "morpheus": {"medallion": {"weight": 59, "count": 2}, "regular": {"weight": 153, "count": 9}},
            "iris": {"medallion": {"weight": 81, "count": 3}, "regular": {"weight": 208, "count": 12}},
            "tucks": {"medallion": {"weight": 71, "count": 2}, "regular": {"weight": 185, "count": 11}},
            "okeanos": {"medallion": {"weight": 66, "count": 2}, "regular": {"weight": 168, "count": 10}},
            "midcity": {"medallion": {"weight": 59, "count": 2}, "regular": {"weight": 153, "count": 9}},
            "thoth": {"medallion": {"weight": 87, "count": 3}, "regular": {"weight": 225, "count": 13}},
            "bacchus": {"medallion": {"weight": 118, "count": 4}, "regular": {"weight": 305, "count": 18}},
            "proteus": {"medallion": {"weight": 93, "count": 3}, "regular": {"weight": 241, "count": 14}},
            "orpheus": {"medallion": {"weight": 105, "count": 4}, "regular": {"weight": 273, "count": 15}}
        },
        "orange": {
            "unaffiliated": {"medallion": {"weight": 8, "count": 0}, "regular": {"weight": 37, "count": 2}},
            "druids": {"medallion": {"weight": 22, "count": 1}, "regular": {"weight": 67, "count": 4}},
            "alla": {"medallion": {"weight": 26, "count": 1}, "regular": {"weight": 52, "count": 3}},
            "chaos": {"medallion": {"weight": 36, "count": 1}, "regular": {"weight": 87, "count": 5}},
            "babylon": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 80, "count": 5}},
            "muses": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "hermes": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 104, "count": 7}},
            "detat": {"medallion": {"weight": 28, "count": 1}, "regular": {"weight": 70, "count": 4}},
            "morpheus": {"medallion": {"weight": 38, "count": 1}, "regular": {"weight": 96, "count": 6}},
            "iris": {"medallion": {"weight": 50, "count": 2}, "regular": {"weight": 128, "count": 7}},
            "tucks": {"medallion": {"weight": 44, "count": 1}, "regular": {"weight": 112, "count": 7}},
            "okeanos": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 104, "count": 7}},
            "midcity": {"medallion": {"weight": 35, "count": 1}, "regular": {"weight": 88, "count": 5}},
            "thoth": {"medallion": {"weight": 53, "count": 2}, "regular": {"weight": 136, "count": 8}},
            "bacchus": {"medallion": {"weight": 71, "count": 2}, "regular": {"weight": 185, "count": 11}},
            "proteus": {"medallion": {"weight": 59, "count": 2}, "regular": {"weight": 153, "count": 9}},
            "orpheus": {"medallion": {"weight": 68, "count": 2}, "regular": {"weight": 177, "count": 11}}
        },
        "black": {
            "unaffiliated": {"medallion": {"weight": 9, "count": 0}, "regular": {"weight": 36, "count": 3}},
            "druids": {"medallion": {"weight": 24, "count": 1}, "regular": {"weight": 68, "count": 4}},
            "alla": {"medallion": {"weight": 22, "count": 1}, "regular": {"weight": 46, "count": 3}},
            "chaos": {"medallion": {"weight": 33, "count": 1}, "regular": {"weight": 82, "count": 5}},
            "babylon": {"medallion": {"weight": 26, "count": 1}, "regular": {"weight": 52, "count": 3}},
            "muses": {"medallion": {"weight": 44, "count": 2}, "regular": {"weight": 112, "count": 6}},
            "hermes": {"medallion": {"weight": 38, "count": 1}, "regular": {"weight": 96, "count": 6}},
            "detat": {"medallion": {"weight": 27, "count": 1}, "regular": {"weight": 62, "count": 4}},
            "morpheus": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 80, "count": 5}},
            "iris": {"medallion": {"weight": 47, "count": 2}, "regular": {"weight": 120, "count": 7}},
            "tucks": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 104, "count": 7}},
            "okeanos": {"medallion": {"weight": 35, "count": 1}, "regular": {"weight": 88, "count": 6}},
            "midcity": {"medallion": {"weight": 28, "count": 1}, "regular": {"weight": 70, "count": 4}},
            "thoth": {"medallion": {"weight": 53, "count": 2}, "regular": {"weight": 136, "count": 8}},
            "bacchus": {"medallion": {"weight": 77, "count": 3}, "regular": {"weight": 201, "count": 12}},
            "proteus": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 145, "count": 9}},
            "orpheus": {"medallion": {"weight": 68, "count": 2}, "regular": {"weight": 177, "count": 11}}
        },
        "silver": {
            "unaffiliated": {"medallion": {"weight": 11, "count": 1}, "regular": {"weight": 56, "count": 2}},
            "druids": {"medallion": {"weight": 34, "count": 1}, "regular": {"weight": 89, "count": 5}},
            "alla": {"medallion": {"weight": 33, "count": 1}, "regular": {"weight": 65, "count": 4}},
            "chaos": {"medallion": {"weight": 48, "count": 2}, "regular": {"weight": 119, "count": 6}},
            "babylon": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 104, "count": 6}},
            "muses": {"medallion": {"weight": 65, "count": 2}, "regular": {"weight": 169, "count": 9}},
            "hermes": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 142, "count": 8}},
            "detat": {"medallion": {"weight": 41, "count": 1}, "regular": {"weight": 104, "count": 6}},
            "morpheus": {"medallion": {"weight": 50, "count": 2}, "regular": {"weight": 128, "count": 7}},
            "iris": {"medallion": {"weight": 71, "count": 2}, "regular": {"weight": 185, "count": 11}},
            "tucks": {"medallion": {"weight": 62, "count": 2}, "regular": {"weight": 161, "count": 9}},
            "okeanos": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 142, "count": 8}},
            "midcity": {"medallion": {"weight": 50, "count": 2}, "regular": {"weight": 128, "count": 7}},
            "thoth": {"medallion": {"weight": 74, "count": 2}, "regular": {"weight": 193, "count": 11}},
            "bacchus": {"medallion": {"weight": 99, "count": 3}, "regular": {"weight": 257, "count": 15}},
            "proteus": {"medallion": {"weight": 81, "count": 3}, "regular": {"weight": 208, "count": 12}},
            "orpheus": {"medallion": {"weight": 93, "count": 3}, "regular": {"weight": 241, "count": 14}}
        },
        "glass": {
            "unaffiliated": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "druids": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "alla": {"medallion": {"weight": 28, "count": 1}, "regular": {"weight": 14, "count": 0}},
            "chaos": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "babylon": {"medallion": {"weight": 56, "count": 2}, "regular": {"weight": 32, "count": 0}},
            "muses": {"medallion": {"weight": 84, "count": 3}, "regular": {"weight": 50, "count": 0}},
            "hermes": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 14, "count": 0}},
            "detat": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "morpheus": {"medallion": {"weight": 64, "count": 2}, "regular": {"weight": 28, "count": 0}},
            "iris": {"medallion": {"weight": 112, "count": 4}, "regular": {"weight": 66, "count": 0}},
            "tucks": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "okeanos": {"medallion": {"weight": 32, "count": 1}, "regular": {"weight": 14, "count": 0}},
            "midcity": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "thoth": {"medallion": {"weight": 64, "count": 2}, "regular": {"weight": 28, "count": 0}},
            "bacchus": {"medallion": {"weight": 168, "count": 6}, "regular": {"weight": 100, "count": 0}},
            "proteus": {"medallion": {"weight": 84, "count": 3}, "regular": {"weight": 50, "count": 0}},
            "orpheus": {"medallion": {"weight": 140, "count": 5}, "regular": {"weight": 84, "count": 0}}
        },
        "lightup": {
            "unaffiliated": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "druids": {"medallion": {"weight": 26, "count": 1}, "regular": {"weight": 12, "count": 0}},
            "alla": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "chaos": {"medallion": {"weight": 52, "count": 2}, "regular": {"weight": 24, "count": 0}},
            "babylon": {"medallion": {"weight": 29, "count": 1}, "regular": {"weight": 13, "count": 0}},
            "muses": {"medallion": {"weight": 104, "count": 4}, "regular": {"weight": 48, "count": 0}},
            "hermes": {"medallion": {"weight": 78, "count": 3}, "regular": {"weight": 36, "count": 0}},
            "detat": {"medallion": {"weight": 26, "count": 1}, "regular": {"weight": 12, "count": 0}},
            "morpheus": {"medallion": {"weight": 52, "count": 2}, "regular": {"weight": 24, "count": 0}},
            "iris": {"medallion": {"weight": 104, "count": 4}, "regular": {"weight": 48, "count": 0}},
            "tucks": {"medallion": {"weight": 130, "count": 5}, "regular": {"weight": 60, "count": 0}},
            "okeanos": {"medallion": {"weight": 78, "count": 3}, "regular": {"weight": 36, "count": 0}},
            "midcity": {"medallion": {"weight": 52, "count": 2}, "regular": {"weight": 24, "count": 0}},
            "thoth": {"medallion": {"weight": 78, "count": 3}, "regular": {"weight": 36, "count": 0}},
            "bacchus": {"medallion": {"weight": 208, "count": 8}, "regular": {"weight": 96, "count": 0}},
            "proteus": {"medallion": {"weight": 104, "count": 4}, "regular": {"weight": 48, "count": 0}},
            "orpheus": {"medallion": {"weight": 182, "count": 7}, "regular": {"weight": 84, "count": 0}}
        },
        "special": {
            "unaffiliated": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "druids": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "alla": {"medallion": {"weight": 37, "count": 1}, "regular": {"weight": 17, "count": 0}},
            "chaos": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "babylon": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "muses": {"medallion": {"weight": 111, "count": 3}, "regular": {"weight": 51, "count": 0}},
            "hermes": {"medallion": {"weight": 74, "count": 2}, "regular": {"weight": 34, "count": 0}},
            "detat": {"medallion": {"weight": 37, "count": 1}, "regular": {"weight": 17, "count": 0}},
            "morpheus": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "iris": {"medallion": {"weight": 74, "count": 2}, "regular": {"weight": 34, "count": 0}},
            "tucks": {"medallion": {"weight": 37, "count": 1}, "regular": {"weight": 17, "count": 0}},
            "okeanos": {"medallion": {"weight": 37, "count": 1}, "regular": {"weight": 17, "count": 0}},
            "midcity": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "thoth": {"medallion": {"weight": 37, "count": 1}, "regular": {"weight": 17, "count": 0}},
            "bacchus": {"medallion": {"weight": 185, "count": 5}, "regular": {"weight": 85, "count": 0}},
            "proteus": {"medallion": {"weight": 111, "count": 3}, "regular": {"weight": 51, "count": 0}},
            "orpheus": {"medallion": {"weight": 148, "count": 4}, "regular": {"weight": 68, "count": 0}}
        },
        "huge": {
            "unaffiliated": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "druids": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "alla": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "chaos": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "babylon": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "muses": {"medallion": {"weight": 58, "count": 1}, "regular": {"weight": 0, "count": 0}},
            "hermes": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "detat": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "morpheus": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "iris": {"medallion": {"weight": 58, "count": 1}, "regular": {"weight": 0, "count": 0}},
            "tucks": {"medallion": {"weight": 116, "count": 2}, "regular": {"weight": 0, "count": 0}},
            "okeanos": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "midcity": {"medallion": {"weight": 0, "count": 0}, "regular": {"weight": 0, "count": 0}},
            "thoth": {"medallion": {"weight": 58, "count": 1}, "regular": {"weight": 0, "count": 0}},
            "bacchus": {"medallion": {"weight": 174, "count": 3}, "regular": {"weight": 0, "count": 0}},
            "proteus": {"medallion": {"weight": 58, "count": 1}, "regular": {"weight": 0, "count": 0}},
            "orpheus": {"medallion": {"weight": 116, "count": 2}, "regular": {"weight": 0, "count": 0}}
        }
    },

    "doubloons": {
        "unaffiliated": {"count": 3},
        "druids": {"count": 4},
        "alla": {"count": 2},
        "chaos": {"count": 5},
        "babylon": {"count": 6},
        "muses": {"count": 8},
        "hermes": {"count": 7},
        "detat": {"count": 3},
        "morpheus": {"count": 4},
        "iris": {"count": 7},
        "tucks": {"count": 6},
        "okeanos": {"count": 5},
        "midcity": {"count": 4},
        "thoth": {"count": 9},
        "bacchus": {"count": 12},
        "proteus": {"count": 8},
        "orpheus": {"count": 11}
    },

    "throws": {
        "items": {
            "cups": {
                "unaffiliated": {"count": 2},
                "druids": {"count": 3},
                "alla": {"count": 4},
                "chaos": {"count": 5},
                "babylon": {"count": 6},
                "muses": {"count": 9},
                "hermes": {"count": 7},
                "detat": {"count": 8},
                "morpheus": {"count": 5},
                "iris": {"count": 11},
                "tucks": {"count": 13},
                "okeanos": {"count": 8},
                "midcity": {"count": 6},
                "thoth": {"count": 10},
                "bacchus": {"count": 18},
                "proteus": {"count": 12},
                "orpheus": {"count": 15}
            },
            "hats": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 1},
                "alla": {"count": 0},
                "chaos": {"count": 2},
                "babylon": {"count": 1},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 1},
                "morpheus": {"count": 1},
                "iris": {"count": 2},
                "tucks": {"count": 4},
                "okeanos": {"count": 2},
                "midcity": {"count": 1},
                "thoth": {"count": 3},
                "bacchus": {"count": 5},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            },
            "sunglasses": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 1},
                "chaos": {"count": 3},
                "babylon": {"count": 2},
                "muses": {"count": 4},
                "hermes": {"count": 3},
                "detat": {"count": 2},
                "morpheus": {"count": 3},
                "iris": {"count": 6},
                "tucks": {"count": 5},
                "okeanos": {"count": 4},
                "midcity": {"count": 3},
                "thoth": {"count": 5},
                "bacchus": {"count": 8},
                "proteus": {"count": 5},
                "orpheus": {"count": 7}
            },
            "balls": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 1},
                "chaos": {"count": 3},
                "babylon": {"count": 2},
                "muses": {"count": 3},
                "hermes": {"count": 4},
                "detat": {"count": 2},
                "morpheus": {"count": 3},
                "iris": {"count": 4},
                "tucks": {"count": 6},
                "okeanos": {"count": 5},
                "midcity": {"count": 4},
                "thoth": {"count": 7},
                "bacchus": {"count": 9},
                "proteus": {"count": 6},
                "orpheus": {"count": 8}
            },
            "footballs": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 1},
                "alla": {"count": 0},
                "chaos": {"count": 2},
                "babylon": {"count": 1},
                "muses": {"count": 0},
                "hermes": {"count": 1},
                "detat": {"count": 1},
                "morpheus": {"count": 2},
                "iris": {"count": 0},
                "tucks": {"count": 3},
                "okeanos": {"count": 2},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 4},
                "proteus": {"count": 2},
                "orpheus": {"count": 3}
            },
            "frisbees": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 1},
                "chaos": {"count": 1},
                "babylon": {"count": 0},
                "muses": {"count": 2},
                "hermes": {"count": 1},
                "detat": {"count": 0},
                "morpheus": {"count": 1},
                "iris": {"count": 1},
                "tucks": {"count": 2},
                "okeanos": {"count": 1},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 3},
                "proteus": {"count": 1},
                "orpheus": {"count": 2}
            },
            "koozies": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 2},
                "chaos": {"count": 3},
                "babylon": {"count": 3},
                "muses": {"count": 5},
                "hermes": {"count": 4},
                "detat": {"count": 4},
                "morpheus": {"count": 3},
                "iris": {"count": 6},
                "tucks": {"count": 7},
                "okeanos": {"count": 5},
                "midcity": {"count": 4},
                "thoth": {"count": 6},
                "bacchus": {"count": 10},
                "proteus": {"count": 7},
                "orpheus": {"count": 9}
            },
            "masks": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 1},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 1},
                "muses": {"count": 2},
                "hermes": {"count": 2},
                "detat": {"count": 3},
                "morpheus": {"count": 2},
                "iris": {"count": 3},
                "tucks": {"count": 2},
                "okeanos": {"count": 2},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 4},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            },
            "keychains": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 1},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 2},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 2},
                "morpheus": {"count": 2},
                "iris": {"count": 4},
                "tucks": {"count": 3},
                "okeanos": {"count": 3},
                "midcity": {"count": 2},
                "thoth": {"count": 3},
                "bacchus": {"count": 5},
                "proteus": {"count": 4},
                "orpheus": {"count": 5}
            },
            "medallions": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 1},
                "alla": {"count": 2},
                "chaos": {"count": 1},
                "babylon": {"count": 1},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 1},
                "morpheus": {"count": 2},
                "iris": {"count": 2},
                "tucks": {"count": 1},
                "okeanos": {"count": 2},
                "midcity": {"count": 1},
                "thoth": {"count": 3},
                "bacchus": {"count": 5},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            },
            "bracelets": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 2},
                "muses": {"count": 4},
                "hermes": {"count": 3},
                "detat": {"count": 2},
                "morpheus": {"count": 2},
                "iris": {"count": 5},
                "tucks": {"count": 3},
                "okeanos": {"count": 3},
                "midcity": {"count": 2},
                "thoth": {"count": 4},
                "bacchus": {"count": 6},
                "proteus": {"count": 4},
                "orpheus": {"count": 5}
            },
            "necklaces": {
                "unaffiliated": {"count": 2},
                "druids": {"count": 3},
                "alla": {"count": 2},
                "chaos": {"count": 4},
                "babylon": {"count": 3},
                "muses": {"count": 6},
                "hermes": {"count": 5},
                "detat": {"count": 4},
                "morpheus": {"count": 4},
                "iris": {"count": 7},
                "tucks": {"count": 6},
                "okeanos": {"count": 5},
                "midcity": {"count": 4},
                "thoth": {"count": 6},
                "bacchus": {"count": 9},
                "proteus": {"count": 7},
                "orpheus": {"count": 8}
            },
            "bandanas": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 1},
                "chaos": {"count": 1},
                "babylon": {"count": 1},
                "muses": {"count": 2},
                "hermes": {"count": 1},
                "detat": {"count": 1},
                "morpheus": {"count": 1},
                "iris": {"count": 2},
                "tucks": {"count": 2},
                "okeanos": {"count": 1},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 3},
                "proteus": {"count": 2},
                "orpheus": {"count": 3}
            },
            "tshirts": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 0},
                "chaos": {"count": 0},
                "babylon": {"count": 0},
                "muses": {"count": 1},
                "hermes": {"count": 0},
                "detat": {"count": 0},
                "morpheus": {"count": 0},
                "iris": {"count": 1},
                "tucks": {"count": 1},
                "okeanos": {"count": 0},
                "midcity": {"count": 0},
                "thoth": {"count": 1},
                "bacchus": {"count": 2},
                "proteus": {"count": 1},
                "orpheus": {"count": 1}
            },
            "blankets": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 0},
                "chaos": {"count": 0},
                "babylon": {"count": 0},
                "muses": {"count": 0},
                "hermes": {"count": 0},
                "detat": {"count": 0},
                "morpheus": {"count": 0},
                "iris": {"count": 1},
                "tucks": {"count": 0},
                "okeanos": {"count": 0},
                "midcity": {"count": 0},
                "thoth": {"count": 1},
                "bacchus": {"count": 1},
                "proteus": {"count": 0},
                "orpheus": {"count": 1}
            },
            "towels": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 1},
                "chaos": {"count": 1},
                "babylon": {"count": 0},
                "muses": {"count": 1},
                "hermes": {"count": 1},
                "detat": {"count": 0},
                "morpheus": {"count": 1},
                "iris": {"count": 2},
                "tucks": {"count": 1},
                "okeanos": {"count": 1},
                "midcity": {"count": 1},
                "thoth": {"count": 1},
                "bacchus": {"count": 2},
                "proteus": {"count": 1},
                "orpheus": {"count": 2}
            },
            "bags": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 1},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 1},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 2},
                "morpheus": {"count": 2},
                "iris": {"count": 3},
                "tucks": {"count": 3},
                "okeanos": {"count": 2},
                "midcity": {"count": 2},
                "thoth": {"count": 3},
                "bacchus": {"count": 5},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            },
            "umbrellas": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 0},
                "chaos": {"count": 0},
                "babylon": {"count": 0},
                "muses": {"count": 1},
                "hermes": {"count": 0},
                "detat": {"count": 0},
                "morpheus": {"count": 0},
                "iris": {"count": 0},
                "tucks": {"count": 1},
                "okeanos": {"count": 1},
                "midcity": {"count": 0},
                "thoth": {"count": 1},
                "bacchus": {"count": 1},
                "proteus": {"count": 1},
                "orpheus": {"count": 1}
            },
            "coolers": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 0},
                "chaos": {"count": 0},
                "babylon": {"count": 0},
                "muses": {"count": 0},
                "hermes": {"count": 0},
                "detat": {"count": 0},
                "morpheus": {"count": 0},
                "iris": {"count": 0},
                "tucks": {"count": 1},
                "okeanos": {"count": 0},
                "midcity": {"count": 0},
                "thoth": {"count": 0},
                "bacchus": {"count": 1},
                "proteus": {"count": 0},
                "orpheus": {"count": 1}
            },
            "lights": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 2},
                "muses": {"count": 4},
                "hermes": {"count": 3},
                "detat": {"count": 3},
                "morpheus": {"count": 2},
                "iris": {"count": 4},
                "tucks": {"count": 5},
                "okeanos": {"count": 3},
                "midcity": {"count": 3},
                "thoth": {"count": 4},
                "bacchus": {"count": 6},
                "proteus": {"count": 4},
                "orpheus": {"count": 5}
            },
            "pens": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 1},
                "alla": {"count": 2},
                "chaos": {"count": 2},
                "babylon": {"count": 2},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 2},
                "morpheus": {"count": 2},
                "iris": {"count": 3},
                "tucks": {"count": 3},
                "okeanos": {"count": 2},
                "midcity": {"count": 2},
                "thoth": {"count": 3},
                "bacchus": {"count": 4},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            },
            "stickers": {
                "unaffiliated": {"count": 2},
                "druids": {"count": 3},
                "alla": {"count": 2},
                "chaos": {"count": 4},
                "babylon": {"count": 3},
                "muses": {"count": 5},
                "hermes": {"count": 4},
                "detat": {"count": 3},
                "morpheus": {"count": 3},
                "iris": {"count": 6},
                "tucks": {"count": 5},
                "okeanos": {"count": 4},
                "midcity": {"count": 3},
                "thoth": {"count": 5},
                "bacchus": {"count": 7},
                "proteus": {"count": 5},
                "orpheus": {"count": 6}
            },
            "fans": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 1},
                "alla": {"count": 1},
                "chaos": {"count": 1},
                "babylon": {"count": 1},
                "muses": {"count": 2},
                "hermes": {"count": 1},
                "detat": {"count": 1},
                "morpheus": {"count": 1},
                "iris": {"count": 2},
                "tucks": {"count": 2},
                "okeanos": {"count": 1},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 3},
                "proteus": {"count": 2},
                "orpheus": {"count": 3}
            },
            "magnets": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 1},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 1},
                "muses": {"count": 2},
                "hermes": {"count": 2},
                "detat": {"count": 1},
                "morpheus": {"count": 1},
                "iris": {"count": 3},
                "tucks": {"count": 2},
                "okeanos": {"count": 2},
                "midcity": {"count": 1},
                "thoth": {"count": 2},
                "bacchus": {"count": 4},
                "proteus": {"count": 2},
                "orpheus": {"count": 3}
            },
            "pins": {
                "unaffiliated": {"count": 1},
                "druids": {"count": 2},
                "alla": {"count": 1},
                "chaos": {"count": 2},
                "babylon": {"count": 2},
                "muses": {"count": 3},
                "hermes": {"count": 2},
                "detat": {"count": 2},
                "morpheus": {"count": 2},
                "iris": {"count": 4},
                "tucks": {"count": 3},
                "okeanos": {"count": 3},
                "midcity": {"count": 2},
                "thoth": {"count": 3},
                "bacchus": {"count": 5},
                "proteus": {"count": 3},
                "orpheus": {"count": 4}
            }
        },
        "stuffedAnimals": {
            "type": {
                "seaAnimals": {"count": 7},
                "bears": {"count": 4},
                "dogs": {"count": 3},
                "cats": {"count": 2},
                "dragons": {"count": 3},
                "alligators": {"count": 2},
                "turtles": {"count": 2},
                "monkeys": {"count": 1},
                "tigers": {"count": 1},
                "lions": {"count": 1},
                "elephants": {"count": 2},
                "giraffes": {"count": 1},
                "unicorns": {"count": 2},
                "dinosaurs": {"count": 2},
                "frogs": {"count": 1},
                "snakes": {"count": 1},
                "birds": {"count": 2},
                "bunnies": {"count": 1},
                "penguins": {"count": 1},
                "koalas": {"count": 1}
            },
            "parade": {
                "unaffiliated": {"count": 0},
                "druids": {"count": 0},
                "alla": {"count": 0},
                "chaos": {"count": 1},
                "babylon": {"count": 0},
                "muses": {"count": 1},
                "hermes": {"count": 0},
                "detat": {"count": 0},
                "morpheus": {"count": 0},
                "iris": {"count": 1},
                "tucks": {"count": 1},
                "okeanos": {"count": 3},
                "midcity": {"count": 2},
                "thoth": {"count": 2},
                "bacchus": {"count": 1},
                "proteus": {"count": 0},
                "orpheus": {"count": 1}
            }
        },
        "specials": {
            "description": {
                "text": "Some parades have a limited set of special, hand decorated, items they throw. Alla throws lamps, Muses shoes, Iris sunglasses, Tucks toilet plungers/brushes, and Orpheus tamborines",
                "parades": {
                    "muses": "shoes",
                    "alla": "lamps",
                    "iris": "sunglasses",
                    "tucks": "plunger/toilet brush",
                    "orpheus": "tamborines"
                }
            },
            "items": {
                "shoes": {"count": 1},
                "lamps": {"count": 0},
                "sunglasses": {"count": 1},
                "plungers": {"count": 2},
                "tamborines": {"count": 1}
            }
        }
    }
};
