// ========================================
// Mardi Gras 2026 - Data
// ========================================
// This file contains all the parade and throws data.
// Edit this file to update your actual counts and weights.
//
// DATA STRUCTURE v2.1:
// - UNAFFILIATED beads categorized by SIZE: small, medium, large, nonSphere, other (medallion/special)
// - PARADE beads categorized by TYPE: medallion or regular
// - Parades include: name, shortName, keyName fields
// - "unaffiliated" represents non-branded beads caught during parades

const mardiGrasData = {
  parades: [
    {
      name: "Krewe of Druids",
      shortName: "Druids",
      keyName: "druids",
      date: "Wed Feb 11 2026",
      time: "6:15 PM",
      logo: "logos/krewe-of-druids.png",
    },
    {
      name: "Krewe of Alla",
      shortName: "Alla",
      keyName: "alla",
      date: "Wed Feb 11 2026",
      time: "7:00 PM",
      logo: "logos/krewe-of-alla.jpg",
    },
    {
      name: "Knights of Chaos",
      shortName: "Chaos",
      keyName: "chaos",
      date: "Thu Feb 12 2026",
      time: "4:30 PM",
      logo: "logos/knights-of-choas.png",
    },
    {
      name: "Knights of Babylon",
      shortName: "Babylon",
      keyName: "babylon",
      date: "Thu Feb 12 2026",
      time: "5:30 PM",
      logo: "logos/knights-of-babylon.png",
    },
    {
      name: "Krewe of Muses",
      shortName: "Muses",
      keyName: "muses",
      date: "Thu Feb 12 2026",
      time: "6:00 PM",
      logo: "logos/krewe-of-muses.jpg",
    },
    {
      name: "Krewe of Hermes",
      shortName: "Hermes",
      keyName: "hermes",
      date: "Fri Feb 13 2026",
      time: "5:30 PM",
      logo: "logos/krewe-of-hermes.jpg",
    },
    {
      name: "Krewe d'Etat",
      shortName: "d'Etat",
      keyName: "detat",
      date: "Fri Feb 13 2026",
      time: "6:30 PM",
      logo: "logos/krewe-d-etat.png",
    },
    {
      name: "Krewe of Morpheus",
      shortName: "Morpheus",
      keyName: "morpheus",
      date: "Fri Feb 13 2026",
      time: "7:00 PM",
      logo: "logos/krewe-of-morpheus.png",
    },
    {
      name: "Krewe of Iris",
      shortName: "Iris",
      keyName: "iris",
      date: "Sat Feb 14 2026",
      time: "11:00 AM",
      logo: "logos/krewe-of-iris.jpg",
    },
    {
      name: "Krewe of Tucks",
      shortName: "Tucks",
      keyName: "tucks",
      date: "Sat Feb 14 2026",
      time: "12:30 PM",
      logo: "logos/krewe-of-tucks.png",
    },
    {
      name: "Krewe of Okeanos",
      shortName: "Okeanos",
      keyName: "okeanos",
      date: "Sun Feb 15 2026",
      time: "11:00 AM",
      logo: "logos/krewe-of-okeanos.png",
    },
    {
      name: "Krewe of Mid-City",
      shortName: "Mid-City",
      keyName: "midcity",
      date: "Sun Feb 15 2026",
      time: "11:45 AM",
      logo: "logos/krewe-of-mid-city.jpg",
    },
    {
      name: "Krewe of Thoth",
      shortName: "Thoth",
      keyName: "thoth",
      date: "Sun Feb 15 2026",
      time: "12:00 PM",
      logo: "logos/krewe-of-thoth.png",
    },
    {
      name: "Krewe of Bacchus",
      shortName: "Bacchus",
      keyName: "bacchus",
      date: "Sun Feb 15 2026",
      time: "5:10 PM",
      logo: "logos/krewe-of-bacchus.png",
    },
    {
      name: "Krewe of Proteus",
      shortName: "Proteus",
      keyName: "proteus",
      date: "Mon Feb 16 2026",
      time: "5:15 PM",
      logo: "logos/krewe-of-proteus.png",
    },
    {
      name: "Krewe of Orpheus",
      shortName: "Orpheus",
      keyName: "orpheus",
      date: "Mon Feb 16 2026",
      time: "6:00 PM",
      logo: "logos/krewe-of-orpheus.png",
    },
  ],

  beadTypes: [
    "black",
    "orange",
    "glass",
    "red",
    "white",
    "blue",
    "pink",
    "silver",
    "green",
    "purple",
    "gold",
    "lightup",
    "special",
    "huge",
  ],

  beads: {
    purple: {
      unaffiliated: {
        small: { weight: 1294, count: 68 },
        medium: { weight: 2869, count: 42 },
        large: { weight: 88, count: 1 },
        nonSphere: { weight: 57, count: 2 },
        other: {
          medallion: { weight: 124, count: 2 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 298, count: 6 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 274, count: 6 },
      },
      tucks: {
        medallion: { weight: 47, count: 1 },
        regular: { weight: 307+60, count: 5+1 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 51, count: 1 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 816+183, count: 9+2 },
      },
    },
    green: {
      unaffiliated: {
        small: { weight: 987+677, count: 38+47 },
        medium: { weight: 2160+2435, count: 32+36 },
        large: { weight: 119, count: 1 },
        nonSphere: { weight: 110, count: 4 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 177, count: 3 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 254+713, count: 5+15 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 146, count: 3 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 89, count: 2 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 32, count: 1 },
        regular: { weight: 82, count: 1 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 284, count: 4 },
      },
    },
    gold: {
      unaffiliated: {
        small: { weight: 21+1625, count: 1+83 },
        medium: { weight: 5241, count: 78 },
        large: { weight: 522, count: 3 },
        nonSphere: { weight: 22+99, count: 1+5 },
        other: {
          medallion: { weight: 44, count: 1 },
          special: { weight: 162, count: 3 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 279, count: 6 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 22, count: 1 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 99, count: 2 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 213, count: 4 },
      },
      thoth: {
        medallion: { weight: 198, count: 5 },
        regular: { weight: 120, count: 3 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 652, count: 5 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 238+589, count: 2+5 },
      },
    },
    red: {
      unaffiliated: {
        small: { weight: 252, count: 15 },
        medium: { weight: 164, count: 3 },
        large: { weight: 154, count: 1 },
        nonSphere: { weight: 76, count: 1 },
        other: {
          medallion: { weight: 48, count: 2 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 486, count: 9},
      },
      thoth: {
        medallion: { weight: 51, count: 2 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 1078, count: 12 },
      },
    },
    blue: {
      unaffiliated: {
        small: { weight: 318, count: 16 },
        medium: { weight: 1467, count: 23 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 956, count: 35 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 68, count: 1 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 137, count: 2 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 89, count: 2 },
        regular: { weight: 204, count: 5 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    pink: {
      unaffiliated: {
        small: { weight: 49, count: 18 },
        medium: { weight: 610, count: 10 },
        large: { weight: 804, count: 5 },
        nonSphere: { weight: 26, count: 1 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 79, count: 1 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 95, count: 2 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 503, count: 7 },
      },
    },
    white: {
      unaffiliated: {
        small: { weight: 39, count: 2 },
        medium: { weight: 2033, count: 36 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    orange: {
      unaffiliated: {
        small: { weight: 55, count: 3 },
        medium: { weight: 76, count: 2 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 45, count: 1 },
        regular: { weight: 154, count: 3 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    black: {
      unaffiliated: {
        small: { weight: 19, count: 1 },
        medium: { weight: 350, count: 5 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    silver: {
      unaffiliated: {
        small: { weight: 340, count: 18 },
        medium: { weight: 1331, count: 19 },
        large: { weight: 341, count: 2 },
        nonSphere: { weight: 12, count: 1 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 1157, count: 40 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 360, count: 8 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 65, count: 1 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 23, count: 1 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 141, count: 2 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    glass: {
      unaffiliated: {
        small: { weight: 0, count: 0 },
        medium: { weight: 45, count: 17 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 29, count: 1 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
    lightup: {
      unaffiliated: {
        small: { weight: 0, count: 0 },
        medium: { weight: 0, count: 0 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 486, count: 5 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 19, count: 1 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 168, count: 5 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 140, count: 4 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 548, count: 9 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 914, count: 12 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 141, count: 2 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 70, count: 3 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 2635, count: 20 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 82, count: 1 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 121, count: 1 },
      },
    },
    special: {
      unaffiliated: {
        small: { weight: 0, count: 0 },
        medium: { weight: 0, count: 0 },
        large: { weight: 0, count: 0 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 2382, count: 32 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 94, count: 1 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 992, count: 8 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 510, count: 10 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 165, count: 1 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 41, count: 1 },
      },
    },
    huge: {
      unaffiliated: {
        small: { weight: 0, count: 0 },
        medium: { weight: 0, count: 0 },
        large: { weight: 1251, count: 9 },
        nonSphere: { weight: 0, count: 0 },
        other: {
          medallion: { weight: 0, count: 0 },
          special: { weight: 0, count: 0 },
        },
      },
      druids: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      alla: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      chaos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      babylon: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      muses: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      hermes: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      detat: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      morpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      iris: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      tucks: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      okeanos: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      midcity: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      thoth: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      bacchus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      proteus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
      orpheus: {
        medallion: { weight: 0, count: 0 },
        regular: { weight: 0, count: 0 },
      },
    },
  },

  doubloons: {
    unaffiliated: { count: 3 },
    druids: { count: 4 },
    alla: { count: 2 },
    chaos: { count: 5 },
    babylon: { count: 6 },
    muses: { count: 8 },
    hermes: { count: 7 },
    detat: { count: 3 },
    morpheus: { count: 4 },
    iris: { count: 7 },
    tucks: { count: 6 },
    okeanos: { count: 5 },
    midcity: { count: 4 },
    thoth: { count: 9 },
    bacchus: { count: 12 },
    proteus: { count: 8 },
    orpheus: { count: 11 },
  },

  throws: {
    items: {
      cups: {
        unaffiliated: { count: 2 },
        druids: { count: 3 },
        alla: { count: 4 },
        chaos: { count: 5 },
        babylon: { count: 6 },
        muses: { count: 9 },
        hermes: { count: 7 },
        detat: { count: 8 },
        morpheus: { count: 5 },
        iris: { count: 11 },
        tucks: { count: 13 },
        okeanos: { count: 8 },
        midcity: { count: 6 },
        thoth: { count: 10 },
        bacchus: { count: 18 },
        proteus: { count: 12 },
        orpheus: { count: 15 },
      },
      hats: {
        unaffiliated: { count: 0 },
        druids: { count: 1 },
        alla: { count: 0 },
        chaos: { count: 2 },
        babylon: { count: 1 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 1 },
        morpheus: { count: 1 },
        iris: { count: 2 },
        tucks: { count: 4 },
        okeanos: { count: 2 },
        midcity: { count: 1 },
        thoth: { count: 3 },
        bacchus: { count: 5 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
      sunglasses: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 1 },
        chaos: { count: 3 },
        babylon: { count: 2 },
        muses: { count: 4 },
        hermes: { count: 3 },
        detat: { count: 2 },
        morpheus: { count: 3 },
        iris: { count: 6 },
        tucks: { count: 5 },
        okeanos: { count: 4 },
        midcity: { count: 3 },
        thoth: { count: 5 },
        bacchus: { count: 8 },
        proteus: { count: 5 },
        orpheus: { count: 7 },
      },
      balls: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 1 },
        chaos: { count: 3 },
        babylon: { count: 2 },
        muses: { count: 3 },
        hermes: { count: 4 },
        detat: { count: 2 },
        morpheus: { count: 3 },
        iris: { count: 4 },
        tucks: { count: 6 },
        okeanos: { count: 5 },
        midcity: { count: 4 },
        thoth: { count: 7 },
        bacchus: { count: 9 },
        proteus: { count: 6 },
        orpheus: { count: 8 },
      },
      footballs: {
        unaffiliated: { count: 0 },
        druids: { count: 1 },
        alla: { count: 0 },
        chaos: { count: 2 },
        babylon: { count: 1 },
        muses: { count: 0 },
        hermes: { count: 1 },
        detat: { count: 1 },
        morpheus: { count: 2 },
        iris: { count: 0 },
        tucks: { count: 3 },
        okeanos: { count: 2 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 4 },
        proteus: { count: 2 },
        orpheus: { count: 3 },
      },
      frisbees: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 1 },
        chaos: { count: 1 },
        babylon: { count: 0 },
        muses: { count: 2 },
        hermes: { count: 1 },
        detat: { count: 0 },
        morpheus: { count: 1 },
        iris: { count: 1 },
        tucks: { count: 2 },
        okeanos: { count: 1 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 3 },
        proteus: { count: 1 },
        orpheus: { count: 2 },
      },
      koozies: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 2 },
        chaos: { count: 3 },
        babylon: { count: 3 },
        muses: { count: 5 },
        hermes: { count: 4 },
        detat: { count: 4 },
        morpheus: { count: 3 },
        iris: { count: 6 },
        tucks: { count: 7 },
        okeanos: { count: 5 },
        midcity: { count: 4 },
        thoth: { count: 6 },
        bacchus: { count: 10 },
        proteus: { count: 7 },
        orpheus: { count: 9 },
      },
      masks: {
        unaffiliated: { count: 0 },
        druids: { count: 1 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 1 },
        muses: { count: 2 },
        hermes: { count: 2 },
        detat: { count: 3 },
        morpheus: { count: 2 },
        iris: { count: 3 },
        tucks: { count: 2 },
        okeanos: { count: 2 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 4 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
      keychains: {
        unaffiliated: { count: 1 },
        druids: { count: 1 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 2 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 2 },
        morpheus: { count: 2 },
        iris: { count: 4 },
        tucks: { count: 3 },
        okeanos: { count: 3 },
        midcity: { count: 2 },
        thoth: { count: 3 },
        bacchus: { count: 5 },
        proteus: { count: 4 },
        orpheus: { count: 5 },
      },
      medallions: {
        unaffiliated: { count: 0 },
        druids: { count: 1 },
        alla: { count: 2 },
        chaos: { count: 1 },
        babylon: { count: 1 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 1 },
        morpheus: { count: 2 },
        iris: { count: 2 },
        tucks: { count: 1 },
        okeanos: { count: 2 },
        midcity: { count: 1 },
        thoth: { count: 3 },
        bacchus: { count: 5 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
      bracelets: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 2 },
        muses: { count: 4 },
        hermes: { count: 3 },
        detat: { count: 2 },
        morpheus: { count: 2 },
        iris: { count: 5 },
        tucks: { count: 3 },
        okeanos: { count: 3 },
        midcity: { count: 2 },
        thoth: { count: 4 },
        bacchus: { count: 6 },
        proteus: { count: 4 },
        orpheus: { count: 5 },
      },
      necklaces: {
        unaffiliated: { count: 2 },
        druids: { count: 3 },
        alla: { count: 2 },
        chaos: { count: 4 },
        babylon: { count: 3 },
        muses: { count: 6 },
        hermes: { count: 5 },
        detat: { count: 4 },
        morpheus: { count: 4 },
        iris: { count: 7 },
        tucks: { count: 6 },
        okeanos: { count: 5 },
        midcity: { count: 4 },
        thoth: { count: 6 },
        bacchus: { count: 9 },
        proteus: { count: 7 },
        orpheus: { count: 8 },
      },
      bandanas: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 1 },
        chaos: { count: 1 },
        babylon: { count: 1 },
        muses: { count: 2 },
        hermes: { count: 1 },
        detat: { count: 1 },
        morpheus: { count: 1 },
        iris: { count: 2 },
        tucks: { count: 2 },
        okeanos: { count: 1 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 3 },
        proteus: { count: 2 },
        orpheus: { count: 3 },
      },
      tshirts: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 0 },
        chaos: { count: 0 },
        babylon: { count: 0 },
        muses: { count: 1 },
        hermes: { count: 0 },
        detat: { count: 0 },
        morpheus: { count: 0 },
        iris: { count: 1 },
        tucks: { count: 1 },
        okeanos: { count: 0 },
        midcity: { count: 0 },
        thoth: { count: 1 },
        bacchus: { count: 2 },
        proteus: { count: 1 },
        orpheus: { count: 1 },
      },
      blankets: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 0 },
        chaos: { count: 0 },
        babylon: { count: 0 },
        muses: { count: 0 },
        hermes: { count: 0 },
        detat: { count: 0 },
        morpheus: { count: 0 },
        iris: { count: 1 },
        tucks: { count: 0 },
        okeanos: { count: 0 },
        midcity: { count: 0 },
        thoth: { count: 1 },
        bacchus: { count: 1 },
        proteus: { count: 0 },
        orpheus: { count: 1 },
      },
      towels: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 1 },
        chaos: { count: 1 },
        babylon: { count: 0 },
        muses: { count: 1 },
        hermes: { count: 1 },
        detat: { count: 0 },
        morpheus: { count: 1 },
        iris: { count: 2 },
        tucks: { count: 1 },
        okeanos: { count: 1 },
        midcity: { count: 1 },
        thoth: { count: 1 },
        bacchus: { count: 2 },
        proteus: { count: 1 },
        orpheus: { count: 2 },
      },
      bags: {
        unaffiliated: { count: 1 },
        druids: { count: 1 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 1 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 2 },
        morpheus: { count: 2 },
        iris: { count: 3 },
        tucks: { count: 3 },
        okeanos: { count: 2 },
        midcity: { count: 2 },
        thoth: { count: 3 },
        bacchus: { count: 5 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
      umbrellas: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 0 },
        chaos: { count: 0 },
        babylon: { count: 0 },
        muses: { count: 1 },
        hermes: { count: 0 },
        detat: { count: 0 },
        morpheus: { count: 0 },
        iris: { count: 0 },
        tucks: { count: 1 },
        okeanos: { count: 1 },
        midcity: { count: 0 },
        thoth: { count: 1 },
        bacchus: { count: 1 },
        proteus: { count: 1 },
        orpheus: { count: 1 },
      },
      coolers: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 0 },
        chaos: { count: 0 },
        babylon: { count: 0 },
        muses: { count: 0 },
        hermes: { count: 0 },
        detat: { count: 0 },
        morpheus: { count: 0 },
        iris: { count: 0 },
        tucks: { count: 1 },
        okeanos: { count: 0 },
        midcity: { count: 0 },
        thoth: { count: 0 },
        bacchus: { count: 1 },
        proteus: { count: 0 },
        orpheus: { count: 1 },
      },
      lights: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 2 },
        muses: { count: 4 },
        hermes: { count: 3 },
        detat: { count: 3 },
        morpheus: { count: 2 },
        iris: { count: 4 },
        tucks: { count: 5 },
        okeanos: { count: 3 },
        midcity: { count: 3 },
        thoth: { count: 4 },
        bacchus: { count: 6 },
        proteus: { count: 4 },
        orpheus: { count: 5 },
      },
      pens: {
        unaffiliated: { count: 1 },
        druids: { count: 1 },
        alla: { count: 2 },
        chaos: { count: 2 },
        babylon: { count: 2 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 2 },
        morpheus: { count: 2 },
        iris: { count: 3 },
        tucks: { count: 3 },
        okeanos: { count: 2 },
        midcity: { count: 2 },
        thoth: { count: 3 },
        bacchus: { count: 4 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
      stickers: {
        unaffiliated: { count: 2 },
        druids: { count: 3 },
        alla: { count: 2 },
        chaos: { count: 4 },
        babylon: { count: 3 },
        muses: { count: 5 },
        hermes: { count: 4 },
        detat: { count: 3 },
        morpheus: { count: 3 },
        iris: { count: 6 },
        tucks: { count: 5 },
        okeanos: { count: 4 },
        midcity: { count: 3 },
        thoth: { count: 5 },
        bacchus: { count: 7 },
        proteus: { count: 5 },
        orpheus: { count: 6 },
      },
      fans: {
        unaffiliated: { count: 0 },
        druids: { count: 1 },
        alla: { count: 1 },
        chaos: { count: 1 },
        babylon: { count: 1 },
        muses: { count: 2 },
        hermes: { count: 1 },
        detat: { count: 1 },
        morpheus: { count: 1 },
        iris: { count: 2 },
        tucks: { count: 2 },
        okeanos: { count: 1 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 3 },
        proteus: { count: 2 },
        orpheus: { count: 3 },
      },
      magnets: {
        unaffiliated: { count: 1 },
        druids: { count: 1 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 1 },
        muses: { count: 2 },
        hermes: { count: 2 },
        detat: { count: 1 },
        morpheus: { count: 1 },
        iris: { count: 3 },
        tucks: { count: 2 },
        okeanos: { count: 2 },
        midcity: { count: 1 },
        thoth: { count: 2 },
        bacchus: { count: 4 },
        proteus: { count: 2 },
        orpheus: { count: 3 },
      },
      pins: {
        unaffiliated: { count: 1 },
        druids: { count: 2 },
        alla: { count: 1 },
        chaos: { count: 2 },
        babylon: { count: 2 },
        muses: { count: 3 },
        hermes: { count: 2 },
        detat: { count: 2 },
        morpheus: { count: 2 },
        iris: { count: 4 },
        tucks: { count: 3 },
        okeanos: { count: 3 },
        midcity: { count: 2 },
        thoth: { count: 3 },
        bacchus: { count: 5 },
        proteus: { count: 3 },
        orpheus: { count: 4 },
      },
    },
    stuffedAnimals: {
      type: {
        seaAnimals: { count: 7 },
        bears: { count: 4 },
        dogs: { count: 3 },
        cats: { count: 2 },
        dragons: { count: 3 },
        alligators: { count: 2 },
        turtles: { count: 2 },
        monkeys: { count: 1 },
        tigers: { count: 1 },
        lions: { count: 1 },
        elephants: { count: 2 },
        giraffes: { count: 1 },
        unicorns: { count: 2 },
        dinosaurs: { count: 2 },
        frogs: { count: 1 },
        snakes: { count: 1 },
        birds: { count: 2 },
        bunnies: { count: 1 },
        penguins: { count: 1 },
        koalas: { count: 1 },
      },
      parade: {
        unaffiliated: { count: 0 },
        druids: { count: 0 },
        alla: { count: 0 },
        chaos: { count: 1 },
        babylon: { count: 0 },
        muses: { count: 1 },
        hermes: { count: 0 },
        detat: { count: 0 },
        morpheus: { count: 0 },
        iris: { count: 1 },
        tucks: { count: 1 },
        okeanos: { count: 3 },
        midcity: { count: 2 },
        thoth: { count: 2 },
        bacchus: { count: 1 },
        proteus: { count: 0 },
        orpheus: { count: 1 },
      },
    },
    specials: {
      description: {
        text: "Some parades have a limited set of special, hand decorated, items they throw. Alla throws lamps, Muses shoes, Iris sunglasses, Tucks toilet plungers/brushes, and Orpheus tamborines",
        parades: {
          muses: "shoes",
          alla: "lamps",
          iris: "sunglasses",
          tucks: "plunger/toilet brush",
          orpheus: "tamborines",
        },
      },
      items: {
        shoes: { count: 1 },
        lamps: { count: 0 },
        sunglasses: { count: 1 },
        plungers: { count: 2 },
        tamborines: { count: 1 },
      },
    },
  },
};
